-- begin WORKSHOP_MECHANIC
alter table WORKSHOP_MECHANIC add constraint FK_WORKSHOP_MECHANIC_ON_USER foreign key (USER_ID) references SEC_USER(ID)^
create index IDX_WORKSHOP_MECHANIC_ON_USER on WORKSHOP_MECHANIC (USER_ID)^
-- end WORKSHOP_MECHANIC
-- begin WORKSHOP_CLIENT
create unique index IDX_WORKSHOP_CLIENT_UNIQ_EMAIL on WORKSHOP_CLIENT (EMAIL) ^
-- end WORKSHOP_CLIENT
-- begin WORKSHOP_SPARE_PART
create unique index IDX_WORKSHOP_SPARE_PART_UNIQ_TITLE on WORKSHOP_SPARE_PART (TITLE) ^
-- end WORKSHOP_SPARE_PART
-- begin WORKSHOP_ORDER
alter table WORKSHOP_ORDER add constraint FK_WORKSHOP_ORDER_ON_CLIENT foreign key (CLIENT_ID) references WORKSHOP_CLIENT(ID)^
alter table WORKSHOP_ORDER add constraint FK_WORKSHOP_ORDER_ON_MECHANIC foreign key (MECHANIC_ID) references WORKSHOP_MECHANIC(ID)^
create index IDX_WORKSHOP_ORDER_ON_CLIENT on WORKSHOP_ORDER (CLIENT_ID)^
create index IDX_WORKSHOP_ORDER_ON_MECHANIC on WORKSHOP_ORDER (MECHANIC_ID)^
-- end WORKSHOP_ORDER
-- begin WORKSHOP_ORDER_SPARE_PART_LINK
alter table WORKSHOP_ORDER_SPARE_PART_LINK add constraint FK_ORDSPAPAR_ON_ORDER foreign key (ORDER_ID) references WORKSHOP_ORDER(ID)^
alter table WORKSHOP_ORDER_SPARE_PART_LINK add constraint FK_ORDSPAPAR_ON_SPARE_PART foreign key (SPARE_PART_ID) references WORKSHOP_SPARE_PART(ID)^
-- end WORKSHOP_ORDER_SPARE_PART_LINK
